### ISSUE TITLE
uopz_set_mock function does not work if xdebug extension is loaded.

### ISSUE THREAD

**Issue by poiwork** [krakjoe/uopz#118] opened 2019-08-31 15:37 UTC
Hello.I'm using uopz now. I face #61 issue problem.

My environment is below:
PHP 7.3.0
Xdebug v2.8.0beta1
uopz 6.1.0
OS mac mojave 10.14.6

Now I write simple code, pasted example1 code below page:

https://www.php.net/manual/ja/function.uopz-set-mock.php

When I do comment out at code below in php.ini file, uopz_set_mock function works expectedly:
zend_extension="xdebug.so" -> ;zend_extension="xdebug.so"

I tried to set xdebug off option "debug.remote_enable = 0" but this function does not work.
Other function, uopz_set_return , uopz_unset_return , uopz_redefine is correctly working.

I run this code 'php' command, not 'phpunit' command.
Please help me.

---------------------------
Now , I did another environment below:
PHP 7.3.9
Xdebug v2.8.0beta1,beta2
uopz 6.1.0
OS linux centos 7.6.1810

Result is same with above environment.
I tested uopz_set_mock function when I checked another problem, using preg_xxx function and fork action logic causes segmentation fault error at child fork process exit timing in PHP 7.3 and MAC OS.

**Comment by krakjoe** [comment] 2019-09-18 11:53
Duplicate of #110, resolution coming in next release (see #119), sorry about delay.

**Closed by krakjoe** 2019-09-18 11:53 UTC

**Comment by poiwork** [comment] 2019-09-20 04:23
> Duplicate of #110, resolution coming in next release (see #119), sorry about delay.

Thanks!
