### ISSUE TITLE
UOPZ + Elementor = PHP Warning:  Cannot modify header information - headers already sent...

### ISSUE THREAD

**Issue by elyran** [krakjoe/uopz#126] opened 2020-06-11 18:43 UTC
Getting an error on v6.1.0:
```
[11-Jun-2020 18:37:10 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php:25) in /var/www/html/wp-includes/pluggable.php on line 1281
[11-Jun-2020 18:37:10 UTC] PHP Stack trace:
[11-Jun-2020 18:37:10 UTC] PHP   1. {main}() /var/www/html/wp-admin/post.php:0
[11-Jun-2020 18:37:10 UTC] PHP   2. wp_redirect() /var/www/html/wp-admin/post.php:358
[11-Jun-2020 18:37:10 UTC] PHP   3. header() /var/www/html/wp-includes/pluggable.php:1281
[11-Jun-2020 18:37:10 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php:25) in /var/www/html/wp-includes/pluggable.php on line 1284
[11-Jun-2020 18:37:10 UTC] PHP Stack trace:
[11-Jun-2020 18:37:10 UTC] PHP   1. {main}() /var/www/html/wp-admin/post.php:0
[11-Jun-2020 18:37:10 UTC] PHP   2. wp_redirect() /var/www/html/wp-admin/post.php:358
[11-Jun-2020 18:37:10 UTC] PHP   3. header() /var/www/html/wp-includes/pluggable.php:1284
```
(the two are similar but not the same - different lines of code, on same file: `pluggable.php`)

Environment:
```
WordPress v5.4.2.
Elementor v2.9.8

PHP 7.3.13 (cli) (built: Dec 18 2019 23:16:14) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.13, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans
```

This happens when I open the Elementor post editor.
A notice about a "server error" is shown on the left-bottom, in a black background.

Here's the faulty request:
```
fetch("http://127.0.0.115/wp-admin/post.php?post=6&action=elementor", {"credentials":"include","headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","accept-language":"en-US,en;q=0.9","cache-control":"no-cache","pragma":"no-cache","sec-fetch-dest":"document","sec-fetch-mode":"navigate","sec-fetch-site":"same-origin","sec-fetch-user":"?1","upgrade-insecure-requests":"1"},"referrer":"http://127.0.0.115/wp-admin/edit.php","referrerPolicy":"strict-origin-when-cross-origin","body":null,"method":"GET","mode":"cors"});
```

When I disable UOPZ the error disappears.

I'm not sure where's the problem, is it with UOPZ or Elementor.

Thanks for UOPZ guys! :)

**Comment by cmb69** [comment] 2020-06-11 20:51
There are known incompatibilites between uopz 6.1.0 and Xdebug 2.9.4+ (or so). If everything works as expected if you disable Xdebug but enable uopz, this ticket is likely a duplicate of #122.

**Comment by cmb69** [comment] 2020-06-11 20:55
Hmm, just saw your comment on the other issue. So this might be because uopz ignores `exit`/`die` by default (see [uopz.exit](https://www.php.net/manual/en/uopz.configuration.php#ini.uopz.exit)).

**Comment by elyran** [comment] 2020-06-11 21:06
Just added `uopz.exit=1` to the INI. No error.

Why would UOPZ disable it? And, by default. What's the reason?
Maybe make this feature inactive by default.

I also wonder how that is going to affect the app. Any doc about the reason of `uopz.exit`?

Anyway, good spotting @cmb69 !

Not sure about closing this issue - I still think this is an issue, maybe not a bug but maybe a design issue. What do you say @cmb69 ?

**Comment by cmb69** [comment] 2020-06-11 21:15
Great that your immediate issue is solved! :)

I think that just ignoring die/exit can make a lot of sense for testing code, but frankly, I don't like that die/exit is ignored by default either (I'm stumbling upon this rather often). Maybe @krakjoe will consider to change the default of `uopz.exit` for the next major version?

**Comment by elyran** [comment] 2020-06-12 12:18
> ignoring die/exit can make a lot of sense for testing code

How?
Can you give a use case?

**Comment by krakjoe** [comment] 2020-12-02 06:36
... history ... uopz replaced test-helpers, one of the main features of that was to ignore exit in tests to allow test suites that used exit in tested units to run to completion. To be a drop in replacement it had to do the same.

It is still acting as that drop in replacement for some people.

This feels to me like a thing that should be mentioned in docs, though I'm not sure where or how ... but there's no bug, so closing this because housekeeping.

**Closed by krakjoe** 2020-12-02 06:36 UTC
